name: Typescript tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ts:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_ACCESS_TOKEN }} # TODO: This token is attached to @jaeaster personal account;
          submodules: recursive                 #       make the contracts repo public or use a github Machine User instead
                                                # Note: Token Expires on Sun, Dec 11 2022

      # Need foundry to build medusa contracts for typechain bindings
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install dependencies for contracts
        working-directory: contracts
        run: forge install

      - name: Build contracts
        working-directory: contracts
        run: forge build

      # npm ci builds typechain bindings because it runs `npm run postinstall`
      - uses: volta-cli/action@v1
      - run: npm ci

      # - name: Build
      #   run: npm run build
      #
      # - name: Format check
      #   run: npm run format:check
      #
      # - name: Lint check
      #   run: npm run lint:check
      #
      # - name: Spell check
      #   run: npm run spell:check

      - name: Test
        run: npm test

      # - name: Setup test
      #   run: npm run test:setup
      #
      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm run semantic-release

