name: Tests

on:
  push:
    branches:
      - master
  pull_request:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  tests:
    runs-on: ubuntu-latest

    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CI_ACCESS_TOKEN }} # TODO: This token is attached to @jaeaster personal account;
          submodules: recursive                 #       make the contracts repo public or use a github Machine User instead
                                                # Note: Token Expires on Sun, Dec 11 2022

      # Need foundry to build medusa contracts for typechain bindings
      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      # npm ci builds contracts + typechain bindings because it runs `npm run postinstall`
      - uses: volta-cli/action@v1
      - run: npm ci

      - name: Lint check
        run: npm run lint

      - name: Test
        run: npm test

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: npm run semantic-release

